// GENERATED by scripts/build-extension.mjs from src/extension/resume-reader.ts — do not edit.
// src/ui/pdf-lines.ts
var DEFAULT_HEIGHT = 10;
var SAME_LINE = 0.5;
var SPACE_GAP = 0.22;
var PARAGRAPH = 1.6;
function median(values) {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0 ? (sorted[mid - 1] + sorted[mid]) / 2 : sorted[mid];
}
function linesFromItems(items) {
  const placed = [];
  for (const it of items) {
    if (!it.str || !it.str.trim()) continue;
    const t = it.transform;
    if (!Array.isArray(t) || t.length < 6) continue;
    placed.push({
      s: it.str,
      x: t[4],
      y: t[5],
      w: typeof it.width === "number" ? it.width : 0,
      h: typeof it.height === "number" && it.height > 0 ? it.height : DEFAULT_HEIGHT
    });
  }
  if (placed.length === 0) return "";
  placed.sort((a, b) => b.y - a.y || a.x - b.x);
  const rows = [];
  let row = [placed[0]];
  let baseline = placed[0].y;
  for (let i = 1; i < placed.length; i++) {
    const p = placed[i];
    if (Math.abs(p.y - baseline) <= p.h * SAME_LINE) {
      row.push(p);
    } else {
      rows.push(row);
      row = [p];
      baseline = p.y;
    }
  }
  rows.push(row);
  const steps = [];
  for (let i = 1; i < rows.length; i++) {
    steps.push(Math.abs(rows[i - 1][0].y - rows[i][0].y));
  }
  const step = median(steps);
  const out = [];
  for (let i = 0; i < rows.length; i++) {
    const items2 = rows[i].slice().sort((a, b) => a.x - b.x);
    let text = items2[0].s;
    for (let k = 1; k < items2.length; k++) {
      const prev = items2[k - 1];
      const cur = items2[k];
      const gap = cur.x - (prev.x + prev.w);
      const needsSpace = gap > cur.h * SPACE_GAP;
      const joined = /\s$/.test(text) || /^\s/.test(cur.s);
      text += needsSpace && !joined ? ` ${cur.s}` : cur.s;
    }
    text = text.replace(/[ \t]+/g, " ").trim();
    if (!text) continue;
    if (i > 0 && step > 0) {
      const drop = Math.abs(rows[i - 1][0].y - rows[i][0].y);
      if (drop > step * PARAGRAPH) out.push("");
    }
    out.push(text);
  }
  return out.join("\n");
}

// src/ui/resume-clean.ts
var ARTEFACT_DIGITS = 8;
var HEADER_LINES = 4;
var SHARED_PREFIX = 5;
var MIN_REPEATS = 2;
function unligature(text) {
  return text.normalize("NFKC");
}
function decodeNumericEntities(text) {
  return text.replace(/&#(\d{1,7});/g, (_, d) => {
    const code = Number(d);
    return code > 0 && code <= 1114111 ? String.fromCodePoint(code) : _;
  }).replace(/&#x([0-9a-fA-F]{1,6});/g, (_, h) => {
    const code = parseInt(h, 16);
    return code > 0 && code <= 1114111 ? String.fromCodePoint(code) : _;
  });
}
function suspectedArtefacts(text) {
  const candidates = [];
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    if (i < HEADER_LINES) continue;
    const t = (lines[i] ?? "").trim();
    if (t.length >= ARTEFACT_DIGITS && /^\d+$/.test(t)) candidates.push({ line: t, at: i + 1 });
  }
  const groups = /* @__PURE__ */ new Map();
  for (const c of candidates) {
    const key = `${c.line.length}:${c.line.slice(0, SHARED_PREFIX)}`;
    const group = groups.get(key);
    if (group) group.push(c);
    else groups.set(key, [c]);
  }
  const out = [];
  for (const group of groups.values()) {
    if (group.length >= MIN_REPEATS) out.push(...group);
  }
  return out.sort((a, b) => a.at - b.at);
}
function suspectsLostSharp(text) {
  if (!/\b(ASP\.NET|VB\.NET|\.NET)\b/i.test(text)) return false;
  for (const line of text.split("\n")) {
    if (!/\b(languages?|skills|programming)\b/i.test(line)) continue;
    if (/\bC#/.test(line) || /\bC\+\+/.test(line)) continue;
    if (/\bC\b(?!\+|#)/.test(line)) return true;
  }
  return false;
}
function cleanResumeText(raw) {
  const repairs = [];
  const warnings = [];
  let text = raw.replace(/\r\n?/g, "\n");
  const unligatured = unligature(text);
  if (unligatured !== text) {
    const before = [...text].filter((c) => {
      const n = c.codePointAt(0) ?? 0;
      return n >= 64256 && n <= 64262;
    }).length;
    if (before > 0) {
      repairs.push(
        `joined ${before} squashed letter${before === 1 ? "" : "s"} (ﬁ, ﬂ, ﬃ) back into ordinary ones — a search for "efficiency" would not have matched "eﬃciency"`
      );
    }
    text = unligatured;
  }
  const decoded = decodeNumericEntities(text);
  if (decoded !== text) {
    repairs.push("decoded character codes left in the text by the converter");
    text = decoded;
  }
  const artefacts = suspectedArtefacts(text);
  if (artefacts.length > 0) {
    warnings.push(
      `Line${artefacts.length === 1 ? "" : "s"} ${artefacts.map((a) => a.at).join(", ")} ${artefacts.length === 1 ? "is a row" : "are rows"} of bare digits (${artefacts.slice(0, 3).map((a) => a.line).join(", ")}). PDF-to-Word converters leave their own object ids behind like this. Nothing has been removed — delete them yourself if they are not yours.`
    );
  }
  if (suspectsLostSharp(text)) {
    warnings.push(
      'Your resume lists "C" on its own beside .NET technologies. A PDF-to-Word converter drops the "#" from "C#", and a reader cannot tell which you meant — check it and fix it if it should be C#.'
    );
  }
  return { text: text.trim(), repairs, warnings };
}

// src/ui/resume-read-core.ts
async function docxText(buf) {
  const xml = await zipEntry(buf, "word/document.xml");
  if (xml === null) throw new Error("no document.xml inside");
  return xml;
}
async function zipEntry(buf, wanted) {
  const view = new DataView(buf);
  const bytes = new Uint8Array(buf);
  let eocd = -1;
  for (let i = bytes.length - 22; i >= 0 && i > bytes.length - 66e3; i--) {
    if (view.getUint32(i, true) === 101010256) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error("not a zip file");
  const count = view.getUint16(eocd + 10, true);
  let at = view.getUint32(eocd + 16, true);
  for (let n = 0; n < count; n++) {
    if (view.getUint32(at, true) !== 33639248) break;
    const method = view.getUint16(at + 10, true);
    const compressedSize = view.getUint32(at + 20, true);
    const nameLen = view.getUint16(at + 28, true);
    const extraLen = view.getUint16(at + 30, true);
    const commentLen = view.getUint16(at + 32, true);
    const localAt = view.getUint32(at + 42, true);
    const name = new TextDecoder().decode(bytes.subarray(at + 46, at + 46 + nameLen));
    if (name === wanted) {
      const localNameLen = view.getUint16(localAt + 26, true);
      const localExtraLen = view.getUint16(localAt + 28, true);
      const start = localAt + 30 + localNameLen + localExtraLen;
      const data = bytes.subarray(start, start + compressedSize);
      if (method === 0) return new TextDecoder().decode(data);
      if (method !== 8) throw new Error(`unsupported compression (${method})`);
      const stream = new Blob([data]).stream().pipeThrough(
        new DecompressionStream("deflate-raw")
      );
      return await new Response(stream).text();
    }
    at += 46 + nameLen + extraLen + commentLen;
  }
  return null;
}
function xmlToText(xml) {
  return xml.replace(/<w:p[ >]/g, "\n<w:p ").replace(/<w:br\s*\/?>/g, "\n").replace(/<w:tab\s*\/?>/g, " ").replace(/<w:instrText\b[^>]*>[\s\S]*?<\/w:instrText>/g, "").replace(/<w:delText\b[^>]*>[\s\S]*?<\/w:delText>/g, "").replace(/<[^>]+>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/[ \t]+/g, " ").replace(/\n{3,}/g, "\n\n").trim();
}
var NEWLINE = String.fromCharCode(10);
var TAB = String.fromCharCode(9);
function stripControlChars(text) {
  let out = "";
  for (const ch of text) {
    const code = ch.codePointAt(0) ?? 0;
    const keep = code >= 32 || ch === NEWLINE || ch === TAB;
    out += keep ? ch : " ";
  }
  return out.split(NEWLINE).map((line) => line.replace(TAB, " ").split(" ").filter(Boolean).join(" ")).join(NEWLINE).trim();
}

// src/ui/resume-profile.ts
var BULLET = /^\s*(?:[•·‣▪●○◦■□►▸✓✔*–—-]|[\uf000-\uf8ff])\s*/;
var SECTION_WORDS = [
  [/^(work |professional |relevant |employment |career )?(experience|employment( history)?|work history|career history|professional background)$/i, "experience"],
  [/^(education|academic (background|qualifications|history)|education (and|&) (training|qualifications|certifications)|qualifications)$/i, "education"],
  [/^(technical |core |key )?(skills|competencies|technologies|tech stack|skills (and|&) (tools|technologies|expertise|interests)|tools( (and|&) technologies)?|expertise)$/i, "skills"],
  [/^languages?( spoken)?$/i, "languages"],
  [/^(projects|personal projects|certifications?|licen[cs]es( (and|&) certifications)?|summary|professional summary|profile|objective|about( me)?|awards|honou?rs|achievements|publications|interests|hobbies|volunteer(ing)?( experience)?|references|activities|leadership|courses|training)$/i, "other"]
];
function knownHeading(line) {
  const t = line.trim().replace(/[:：]$/, "").trim();
  return SECTION_WORDS.some(([re]) => re.test(t));
}
function headingOf(line) {
  const t = line.trim().replace(/[:：]$/, "").trim();
  if (!t || t.length > 48) return null;
  if (/[.,;!?]$/.test(t)) return null;
  if (DATE_RANGE.test(t)) return null;
  for (const [re, section] of SECTION_WORDS) if (re.test(t)) return section;
  const letters = t.replace(/[^A-Za-z]/g, "");
  if (letters.length >= 4 && t === t.toUpperCase() && t.split(/\s+/).length <= 5) return "other";
  return null;
}
var MONTH_NAMES = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];
var MONTH = "(?:jan|feb|mar|apr|may|jun|jul|aug|sep|sept|oct|nov|dec)[a-z]*\\.?";
var YEAR = "(?:19|20)\\d{2}";
var DATE_TOKEN = `(?:${MONTH}\\s*[',]?\\s*${YEAR}|\\d{1,2}\\s*[/.-]\\s*${YEAR}|${YEAR}\\s*[/.-]\\s*\\d{1,2}(?!\\d)|${YEAR})`;
var DATE_END = `(?:${DATE_TOKEN}|present|current|now|today|ongoing|date)`;
var DATE_RANGE = new RegExp(`(${DATE_TOKEN})\\s*(?:-|–|—|to|until|through|till)\\s*(${DATE_END})`, "i");
function parseDate(token) {
  const t = token.trim().toLowerCase();
  let m = new RegExp(`^(${MONTH})\\s*[',]?\\s*(${YEAR})$`, "i").exec(t);
  if (m) return { y: Number(m[2]), m: MONTH_NAMES.indexOf(m[1].slice(0, 3)) + 1 };
  m = new RegExp(`^(\\d{1,2})\\s*[/.-]\\s*(${YEAR})$`).exec(t);
  if (m && Number(m[1]) >= 1 && Number(m[1]) <= 12) return { y: Number(m[2]), m: Number(m[1]) };
  m = new RegExp(`^(${YEAR})\\s*[/.-]\\s*(\\d{1,2})$`).exec(t);
  if (m && Number(m[2]) >= 1 && Number(m[2]) <= 12) return { y: Number(m[1]), m: Number(m[2]) };
  m = new RegExp(`^(${YEAR})$`).exec(t);
  if (m) return { y: Number(m[1]), m: 0 };
  return null;
}
var isOngoing = (token) => /^(present|current|now|today|ongoing|date)$/i.test(token.trim());
function fromStored(s) {
  const m = /^(\d{4})(?:-(\d{2}))?$/.exec(s.trim());
  return m ? { y: Number(m[1]), m: m[2] ? Number(m[2]) : 0 } : null;
}
function formatDate(d) {
  if (!d) return "";
  return d.m ? `${d.y}-${String(d.m).padStart(2, "0")}` : String(d.y);
}
var TITLE_WORDS = /\b(engineer|developer|programmer|architect|manager|director|lead|head|analyst|scientist|designer|consultant|specialist|intern|internship|associate|assistant|coordinator|administrator|officer|executive|president|vp|founder|co-?founder|owner|partner|technician|representative|advisor|adviser|strategist|researcher|fellow|trainee|apprentice|editor|writer|producer|accountant|auditor|nurse|teacher|lecturer|professor|instructor|tutor|recruiter|sales|marketing|operator|supervisor|agent|clerk|cashier|chef|driver|attorney|lawyer|paralegal|physician|therapist|pharmacist|product owner|scrum master|sre|devops|qa|tester|cto|ceo|cfo|coo|cio|member of technical staff|staff|principal|contractor|freelancer?|volunteer)\b/i;
var COMPANY_HINT = /\b(inc|llc|ltd|limited|corp|corporation|company|co\.|gmbh|ag|plc|pvt|private|technologies|technology|solutions|systems|labs|software|consulting|services|group|holdings|bank|capital|partners|studio|studios|agency|media|health|hospital|university|foundation|institute)\b/i;
var SCHOOL_WORDS = /\b(university|universit[äa]t|universidad|universit[ée]|college|institute|institut|school|academy|polytechnic|conservatory|iit|nit|iiit|bits|mit|ucla|nyu|lse)\b/i;
var DEGREES = [
  { words: /\b(ph\.?\s?d|doctor(ate)? of|doctorate|d\.?phil)\b/i, abbr: /\b(PhD|Ph\.D\.?|DPhil|EdD|MD|JD)\b/, rank: 6 },
  { words: /\b(m\.?b\.?a|master of business administration)\b/i, abbr: /\bMBA\b/, rank: 5 },
  { words: /\b(master'?s?|m\.?sc|m\.?tech|m\.?eng|m\.?phil|m\.?com|ll\.?m|m\.?res)\b/i, abbr: /\b(M\.?S\.?|M\.?A\.?|M\.?E\.?|MCA|M\.?Ed|MPH|MFA|MIS)\b/, rank: 4 },
  { words: /\b(bachelor'?s?|b\.?sc|b\.?tech|b\.?eng|b\.?com|ll\.?b|b\.?arch|undergraduate degree)\b/i, abbr: /\b(B\.?S\.?|B\.?A\.?|B\.?E\.?|BCA|BBA|B\.?Ed|BFA|A\.?B\.?)\b/, rank: 3 },
  { words: /\bassociate'?s?( degree| of)\b/i, abbr: /\b(A\.?A\.?S?|A\.?S\.?)\b/, rank: 2 },
  { words: /\b(diploma|certificate|hnd|hnc|foundation degree)\b/i, abbr: /(?!)/, rank: 1 },
  { words: /\b(high school|secondary school|a[- ]levels?|gcse|ssc|hsc|12th|10th)\b/i, abbr: /(?!)/, rank: 0 }
];
var US_STATES = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  DC: "District of Columbia"
};
var CA_PROVINCE_NAMES = {
  ON: "Ontario",
  QC: "Quebec",
  BC: "British Columbia",
  AB: "Alberta",
  MB: "Manitoba",
  SK: "Saskatchewan",
  NS: "Nova Scotia",
  NB: "New Brunswick",
  NL: "Newfoundland and Labrador",
  PE: "Prince Edward Island",
  YT: "Yukon",
  NT: "Northwest Territories",
  NU: "Nunavut"
};
var CA_PROVINCES = /^(ON|QC|BC|AB|MB|SK|NS|NB|NL|PE|YT|NT|NU|Ontario|Quebec|British Columbia|Alberta|Manitoba|Saskatchewan|Nova Scotia|New Brunswick|Newfoundland( and Labrador)?|Prince Edward Island)$/i;
var COUNTRIES = /^(united states( of america)?|usa|us|u\.s\.a?\.?|united kingdom|uk|u\.k\.|england|scotland|wales|ireland|canada|india|germany|france|spain|portugal|italy|netherlands|belgium|switzerland|austria|sweden|norway|denmark|finland|poland|czech republic|czechia|romania|hungary|greece|turkey|israel|uae|united arab emirates|saudi arabia|qatar|egypt|nigeria|kenya|south africa|ghana|australia|new zealand|singapore|malaysia|indonesia|philippines|vietnam|thailand|japan|south korea|korea|china|hong kong|taiwan|pakistan|bangladesh|sri lanka|nepal|brazil|mexico|argentina|chile|colombia|peru|uruguay|estonia|latvia|lithuania|ukraine|luxembourg|iceland|cyprus|malta)$/i;
var COUNTRY_NAME = {
  usa: "United States",
  us: "United States",
  "u.s.a.": "United States",
  "u.s.a": "United States",
  "u.s.": "United States",
  "united states of america": "United States",
  uk: "United Kingdom",
  "u.k.": "United Kingdom",
  uae: "United Arab Emirates"
};
var clean = (s) => s.replace(/\s+/g, " ").trim();
var stripEdges = (s) => clean(s).replace(/^[\s,|·•–—:-]+|[\s,|·•–—:-]+$/g, "").trim();
function titleCase(s) {
  if (s !== s.toUpperCase()) return s;
  return s.toLowerCase().replace(/(^|[\s'-])([a-z])/g, (_m, pre, c) => pre + c.toUpperCase());
}
function partsOf(line) {
  return line.split(/\s+[|·•]\s+|\s[–—]\s|\s-\s|\s{3,}|\t|\s+@\s+|\s+at\s+(?=[A-Z])/).map(stripEdges).filter(Boolean).flatMap(splitCommas);
}
function splitCommas(part) {
  if (!part.includes(",") || looksLikePlace(part)) return [part];
  const bits = part.split(/\s*,\s*/).filter(Boolean);
  for (let i = 1; i < bits.length; i++) {
    const tail = bits.slice(i).join(", ");
    if (looksLikePlace(tail)) return [...splitCommas(bits.slice(0, i).join(", ")), tail];
  }
  const head = bits[0];
  const rest = bits.slice(1).join(", ");
  if (/^(inc|llc|ltd|co|corp|gmbh|plc)\.?$/i.test(rest)) return [part];
  if (TITLE_WORDS.test(head) !== TITLE_WORDS.test(rest)) return [head, rest];
  if (degreeRank(head) >= 0 !== degreeRank(rest) >= 0 || SCHOOL_WORDS.test(head) !== SCHOOL_WORDS.test(rest)) {
    return [head, rest];
  }
  return [part];
}
function looksLikePlace(s) {
  const t = s.trim();
  if (/^(remote|hybrid|on-?site)$/i.test(t)) return true;
  if (/\d|@|https?:|www\./i.test(t)) return false;
  const bits = t.split(/\s*,\s*/);
  if (bits.length < 2 || bits.length > 3) return COUNTRIES.test(t);
  const last = bits[bits.length - 1];
  if (bits.length === 3) return COUNTRIES.test(last);
  return /^[A-Z]{2}$/.test(last) || COUNTRIES.test(last) || CA_PROVINCES.test(last) || Object.values(US_STATES).some((n) => n.toLowerCase() === last.toLowerCase());
}
var EMAIL = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i;
function findPhone(text) {
  const candidates = text.match(/(?:\+\s?)?\(?\d[\d\s().-]{6,}\d/g) ?? [];
  for (const raw of candidates) {
    const c = raw.trim();
    if (/\//.test(c)) continue;
    const groups = c.match(/\d+/g) ?? [];
    if (groups.every((g) => /^(19|20)\d{2}$/.test(g))) continue;
    const digits = c.replace(/\D/g, "");
    const plus = c.startsWith("+");
    if (digits.length > 15) continue;
    if (digits.length >= 10 || plus && digits.length >= 8) return clean(c);
  }
  return "";
}
function normaliseUrl(u) {
  const t = u.trim().replace(/[),.;]+$/, "");
  return /^https?:\/\//i.test(t) ? t : `https://${t}`;
}
function findLinkedin(hay) {
  const m = /(?:https?:\/\/)?(?:[a-z]{2,3}\.)?linkedin\.com\/in\/([A-Za-z0-9_%-]+)/i.exec(hay);
  return m ? `https://www.linkedin.com/in/${m[1]}` : "";
}
function findGithub(hay) {
  const m = /(?:https?:\/\/)?(?:www\.)?github\.com\/([A-Za-z0-9](?:[A-Za-z0-9-]{0,38}))(?![A-Za-z0-9-])/i.exec(hay);
  if (!m || /^(orgs|topics|features|about|pricing|login)$/i.test(m[1])) return "";
  return `https://github.com/${m[1]}`;
}
var SITE = /\b(?:https?:\/\/)?(?:www\.)?[a-z0-9][a-z0-9-]*(?:\.[a-z0-9-]+)*\.(?:com|dev|io|me|net|org|co|app|ai|tech|site|xyz|info|design|page|blog|codes|portfolio|online)(?:\/[^\s|,)]*)?/gi;
function findWebsite(topText, links) {
  const skip = /linkedin\.com|github\.com|mailto:|tel:|google\.com|gmail\.com|outlook\.com|yahoo\.com|hotmail\.com|icloud\.com/i;
  for (const l of links) if (/^https?:\/\//i.test(l) && !skip.test(l)) return l.replace(/\/$/, "");
  const noEmails = topText.replace(new RegExp(EMAIL.source, "gi"), " ");
  for (const m of noEmails.match(SITE) ?? []) {
    if (!skip.test(m)) return normaliseUrl(m).replace(/\/$/, "");
  }
  return "";
}
function findPlace(lines, name) {
  for (const line of lines) {
    for (const part of line.split(/\s*[|·•]\s*|\s{2,}|\s[–—-]\s/).map(stripEdges)) {
      if (!part || part === name || EMAIL.test(part) || TITLE_WORDS.test(part)) continue;
      if (/^(remote|hybrid)$/i.test(part)) continue;
      if (!looksLikePlace(part)) continue;
      const bits = part.split(/\s*,\s*/).map((b) => b.trim());
      if (bits.length === 1) return { city: "", region: "", country: countryName(bits[0]) };
      const [city, second, third] = bits;
      if (third) return { city, region: second, country: countryName(third) };
      if (/^[A-Z]{2}$/.test(second) && US_STATES[second]) return { city, region: US_STATES[second], country: "United States" };
      if (CA_PROVINCES.test(second)) return { city, region: CA_PROVINCE_NAMES[second.toUpperCase()] ?? second, country: "Canada" };
      if (COUNTRIES.test(second)) return { city, region: "", country: countryName(second) };
      return { city, region: second, country: "" };
    }
  }
  return null;
}
function countryName(s) {
  return COUNTRY_NAME[s.toLowerCase()] ?? titleCase(s);
}
function findName(lines) {
  for (const raw of lines.slice(0, 5)) {
    const first = stripEdges(raw.split(/\s*[|·•]\s*|\s{2,}/)[0] ?? "");
    if (!first) continue;
    if (/^(resume|résumé|curriculum vitae|cv)$/i.test(first)) continue;
    if (/[\d@/:]/.test(first)) continue;
    const words = first.split(/\s+/);
    if (words.length < 2 || words.length > 4) continue;
    if (!words.every((w) => /^[\p{L}][\p{L}.'-]*$/u.test(w))) continue;
    if (knownHeading(first)) continue;
    return titleCase(first);
  }
  return "";
}
function isBullet(line) {
  return BULLET.test(line) && !/^\s*-?\d/.test(line);
}
function headerLike(line) {
  const t = line.trim();
  if (!t || isBullet(t) || t.length > 90) return false;
  if (/[.;]$/.test(t) && !/\b(inc|ltd|co|corp)\.$/i.test(t)) return false;
  return t.split(/\s+/).length <= 12;
}
function readJobs(section) {
  const jobs = [];
  const used = /* @__PURE__ */ new Set();
  const heads = [];
  for (let i = 0; i < section.length; i++) {
    const line = section[i];
    const range = DATE_RANGE.exec(line);
    if (!range) continue;
    if (isBullet(line) && line.replace(BULLET, "").length > 60) continue;
    const rest = stripEdges(line.slice(0, range.index) + " " + line.slice(range.index + range[0].length));
    const candidates = [];
    for (const p of partsOf(rest)) candidates.push({ text: p, from: "same" });
    let first = i;
    let last = i;
    for (let k = i - 1, taken = 0; k >= 0 && taken < 2; k--) {
      const prev = section[k];
      if (!prev.trim() || used.has(k) || !headerLike(prev) || DATE_RANGE.test(prev)) break;
      for (const p of partsOf(prev)) candidates.push({ text: p, from: "before" });
      used.add(k);
      first = k;
      taken++;
    }
    const haveBoth = () => candidates.some((c) => TITLE_WORDS.test(c.text)) && candidates.some((c) => !TITLE_WORDS.test(c.text) && !looksLikePlace(c.text));
    for (let k = i + 1, taken = 0; k < section.length && taken < 2 && !haveBoth(); k++) {
      const next = section[k];
      if (!next.trim() || !headerLike(next) || DATE_RANGE.test(next)) break;
      for (const p of partsOf(next)) candidates.push({ text: p, from: "after" });
      used.add(k);
      last = k;
      taken++;
    }
    used.add(i);
    const places = candidates.filter((c) => looksLikePlace(c.text));
    const others = candidates.filter((c) => !looksLikePlace(c.text));
    const titled = others.filter((c) => TITLE_WORDS.test(c.text));
    let title = (titled.find((c) => !COMPANY_HINT.test(c.text)) ?? titled[0])?.text ?? "";
    const untitled = others.filter((c) => c.text !== title && !TITLE_WORDS.test(c.text));
    let company = (untitled.find((c) => COMPANY_HINT.test(c.text)) ?? untitled[0])?.text ?? "";
    if (!title && !company && others.length >= 2) {
      company = others[0].text;
      title = others[1].text;
    } else if (!title && company) {
      title = others.find((c) => c.text !== company)?.text ?? "";
    } else if (title && !company) {
      company = others.find((c) => c.text !== title)?.text ?? "";
    }
    const start = parseDate(range[1]);
    const ongoing = isOngoing(range[2]);
    const end = ongoing ? null : parseDate(range[2]);
    jobs.push({
      company: company.replace(/,\s*$/, ""),
      title,
      location: places[0]?.text ?? "",
      start: formatDate(start),
      end: formatDate(end),
      current: ongoing
    });
    heads.push({ first, last });
  }
  jobs.forEach((job, j) => {
    const body = section.slice(heads[j].last + 1, heads[j + 1]?.first ?? section.length).map((l) => l.replace(BULLET, "").trim()).filter((l) => l.length > 2);
    if (body.length) job.description = body.join("\n").slice(0, 2e3);
  });
  return jobs.filter((j) => j.company || j.title);
}
function yearsOf(jobs, today) {
  const spans = [];
  for (const j of jobs) {
    const s = fromStored(j.start);
    if (!s) continue;
    const startM = s.y * 12 + (s.m ? s.m - 1 : 0);
    let endM;
    if (j.current) endM = today.getFullYear() * 12 + today.getMonth();
    else {
      const e = fromStored(j.end);
      if (!e) continue;
      endM = e.y * 12 + (e.m ? e.m - 1 : 0);
    }
    if (endM > startM) spans.push([startM, endM]);
  }
  if (!spans.length) return null;
  spans.sort((a, b) => a[0] - b[0]);
  let total = 0;
  let [curS, curE] = spans[0];
  for (const [s, e] of spans.slice(1)) {
    if (s <= curE) curE = Math.max(curE, e);
    else {
      total += curE - curS;
      [curS, curE] = [s, e];
    }
  }
  total += curE - curS;
  const first = spans[0][0];
  const from = `${MONTH_NAMES[first % 12].replace(/^./, (c) => c.toUpperCase())} ${Math.floor(first / 12)}`;
  return { years: Math.floor(total / 12), from };
}
function degreeRank(text) {
  for (const d of DEGREES) if (d.words.test(text) || d.abbr.test(text)) return d.rank;
  return -1;
}
function splitDegree(text) {
  const t = stripEdges(text);
  const inX = /^(.+?)\s+in\s+(.+)$/i.exec(t);
  if (inX && degreeRank(inX[1]) >= 0) return { degree: stripEdges(inX[1]), discipline: stripEdges(inX[2]) };
  const paren = /^(.*?)\s*\(([^)]+)\)\s*$/.exec(t);
  if (paren && degreeRank(paren[1]) >= 0 && !/^(hons|honours|honors)$/i.test(paren[2])) {
    return { degree: stripEdges(paren[1]), discipline: stripEdges(paren[2]) };
  }
  const comma = /^([^,]+?)\s*[,:–—]\s*(.+)$/.exec(t);
  if (comma && degreeRank(comma[1]) >= 0 && degreeRank(comma[2]) < 0) {
    return { degree: stripEdges(comma[1]), discipline: stripEdges(comma[2]) };
  }
  const abbr = /^(\S+(?:\s*\((?:hons|honours|honors)\))?)\s+(.+)$/i.exec(t);
  if (abbr && degreeRank(abbr[1]) >= 0 && degreeRank(abbr[2]) < 0 && !/^of\b/i.test(abbr[2])) {
    return { degree: stripEdges(abbr[1]), discipline: stripEdges(abbr[2]) };
  }
  return { degree: t, discipline: "" };
}
function readSchools(section) {
  const schools = [];
  let cur = null;
  const fresh = () => ({ school: "", degree: "", discipline: "", start: "", end: "", gpa: "" });
  const flush = () => {
    if (cur && (cur.school || cur.degree)) schools.push(cur);
    cur = null;
  };
  for (const raw of section) {
    if (!raw.trim()) continue;
    const line = raw.replace(BULLET, "");
    let rest = line;
    let gpa = "";
    const g = /\b(?:c?gpa|grade point average|cgpa)\s*[:\-]?\s*(\d+(?:\.\d+)?(?:\s*\/\s*\d+(?:\.\d+)?)?)/i.exec(rest) ?? /\b(\d\.\d{1,2}\s*\/\s*(?:4|5|10)(?:\.0+)?)\b/.exec(rest);
    if (g) {
      gpa = g[1].replace(/\s+/g, "");
      rest = rest.replace(g[0], " ");
    }
    let start = "";
    let end = "";
    const range = DATE_RANGE.exec(rest);
    if (range) {
      start = formatDate(parseDate(range[1]));
      end = isOngoing(range[2]) ? "" : formatDate(parseDate(range[2]));
      rest = rest.replace(range[0], " ");
    } else {
      const single = new RegExp(`(?:expected|graduat\\w*|class of|completed)?\\s*(${DATE_TOKEN})`, "i").exec(rest);
      if (single) {
        end = formatDate(parseDate(single[1]));
        rest = rest.replace(single[0], " ");
      }
    }
    const parts = partsOf(rest);
    for (const part of parts.length ? parts : [stripEdges(rest)]) {
      if (!part) continue;
      const isSchool = SCHOOL_WORDS.test(part) && degreeRank(part) < 0;
      const isDegree = degreeRank(part) >= 0 && !(SCHOOL_WORDS.test(part) && /\b(school|college|university)\b/i.test(part) && degreeRank(part) === 0 && !/high school diploma/i.test(part));
      if (isSchool) {
        if (cur && cur.school) flush();
        cur ??= fresh();
        cur.school = part.replace(/,\s*[A-Z][a-z]+(,\s*[A-Z]{2,})?$/, "").trim();
      } else if (isDegree) {
        if (cur && cur.degree) flush();
        cur ??= fresh();
        const d = splitDegree(part);
        cur.degree = d.degree;
        cur.discipline = d.discipline;
      }
    }
    if (cur) {
      const c = cur;
      if (gpa && !c.gpa) c.gpa = gpa;
      if (start && !c.start) c.start = start;
      if (end && !c.end) c.end = end;
    }
  }
  flush();
  return schools;
}
function readSkills(section) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const raw of section) {
    const line = raw.replace(BULLET, "").trim();
    if (!line) continue;
    const body = line.includes(":") && line.indexOf(":") < 50 ? line.slice(line.indexOf(":") + 1) : line;
    for (const piece of body.split(/\s*[,|•·;]\s*|\s{2,}/)) {
      const s = stripEdges(piece).replace(/^(and|&)\s+/i, "");
      if (!s || s.length > 40 || s.split(/\s+/).length > 5) continue;
      const k = s.toLowerCase();
      if (seen.has(k)) continue;
      seen.add(k);
      out.push(s);
      if (out.length >= 60) return out;
    }
  }
  return out;
}
function profileFromResume(text, opts = {}) {
  const today = opts.today ?? /* @__PURE__ */ new Date();
  const links = (opts.links ?? []).map((l) => l.trim()).filter(Boolean);
  const lines = text.replace(/\r\n?/g, "\n").split("\n").map((l) => l.replace(/\s+$/, ""));
  const sections = { top: [], experience: [], education: [], skills: [], languages: [], other: [] };
  let current = "top";
  for (const line of lines) {
    const heading = headingOf(line);
    if (heading && (current !== "top" || sections.top.some((l) => l.trim()))) {
      current = heading;
      continue;
    }
    sections[current].push(line);
  }
  const noHeadings = !sections.experience.length && !sections.education.length;
  const jobLines = noHeadings ? lines : sections.experience;
  const profile = { details: {}, answers: {}, experience: [], education: [], skills: [], notes: [] };
  const d = profile.details;
  const topLines = sections.top.filter((l) => l.trim()).slice(0, 12);
  const topText = topLines.join("\n");
  const everything = `${text}
${links.join("\n")}`;
  const name = findName(topLines.length ? topLines : lines.filter((l) => l.trim()));
  if (name) {
    const words = name.split(/\s+/);
    d.firstName = words[0];
    d.lastName = words[words.length - 1];
    if (words.length > 2) d.middleName = words.slice(1, -1).join(" ");
  }
  const email = EMAIL.exec(everything.replace(/mailto:/gi, " "));
  if (email) d.email = email[0];
  const phone = findPhone(topText) || findPhone(text.split("\n").slice(0, 30).join("\n"));
  if (phone) d.phone = phone;
  const linkedin = findLinkedin(everything);
  if (linkedin) d.linkedin = linkedin;
  const github = findGithub(everything);
  if (github) d.github = github;
  const website = findWebsite(topText, links);
  if (website) d.website = website;
  const place = findPlace(topLines, name);
  if (place) {
    if (place.city) d.city = place.city;
    if (place.region) d.region = place.region;
    if (place.country) d.country = place.country;
  }
  profile.experience = readJobs(jobLines);
  profile.education = readSchools(sections.education);
  profile.skills = readSkills(sections.skills);
  const latest = profile.experience.find((j) => j.current) ?? profile.experience[0];
  if (latest) {
    if (latest.company) d.currentCompany = latest.company;
    if (latest.title) d.currentTitle = latest.title;
  }
  if (profile.experience.some((j) => j.current)) {
    profile.answers.currentlyEmployed = "Yes";
    profile.notes.push(`Currently employed: yes, because ${latest?.company || "a job"} runs to "Present".`);
  }
  const years = yearsOf(profile.experience, today);
  if (years) {
    profile.answers.yearsExperience = String(years.years);
    profile.notes.push(
      `Years of experience: ${years.years}, counted from ${profile.experience.length} job${profile.experience.length === 1 ? "" : "s"} starting ${years.from}. Overlapping jobs count once, and it is rounded down. Change it if you count differently.`
    );
  }
  const best = [...profile.education].sort((a, b) => degreeRank(b.degree) - degreeRank(a.degree))[0];
  if (best && (best.degree || best.school)) {
    profile.answers.education = [
      [best.degree, best.discipline].filter(Boolean).join(" in "),
      best.school,
      best.end.slice(0, 4)
    ].filter(Boolean).join(", ");
  }
  const spoken = sections.languages.map((l) => l.replace(BULLET, "").trim()).filter(Boolean);
  const inSkills = sections.skills.map((l) => /^\s*(spoken )?languages?\s*:\s*(.+)$/i.exec(l.replace(BULLET, ""))?.[2]).find(Boolean);
  const languages = spoken.length ? spoken.join(", ") : inSkills ?? "";
  if (languages && !/\b(python|java|javascript|typescript|c\+\+|sql|golang|rust|ruby|php)\b/i.test(languages)) {
    profile.answers.languages = clean(languages);
  }
  return profile;
}

// src/extension/resume-reader.ts
async function pdfRead(buf, where) {
  const pdfjs = await import(
    /* @vite-ignore */
    where.lib
  );
  pdfjs.GlobalWorkerOptions.workerSrc = where.worker;
  const doc = await pdfjs.getDocument({ data: new Uint8Array(buf), isEvalSupported: false }).promise;
  const pages = [];
  const links = [];
  for (let n = 1; n <= Math.min(doc.numPages, 10); n++) {
    const page = await doc.getPage(n);
    const content = await page.getTextContent();
    pages.push(linesFromItems(content.items));
    for (const a of await page.getAnnotations()) {
      const url = a.url || a.unsafeUrl;
      if (a.subtype === "Link" && url) links.push(url);
    }
  }
  await doc.destroy();
  return { text: pages.join("\n\n"), links };
}
async function docxRead(buf) {
  const text = xmlToText(await docxText(buf));
  const rels = await zipEntry(buf, "word/_rels/document.xml.rels") ?? "";
  const links = [...rels.matchAll(/Target="(https?:[^"]+|mailto:[^"]+)"/g)].map((m) => m[1].replace(/&amp;/g, "&"));
  return { text, links };
}
async function readResume(file, where, today = /* @__PURE__ */ new Date()) {
  const name = file.name.toLowerCase();
  const empty = (warning2) => ({
    text: "",
    links: [],
    profile: profileFromResume("", { today }),
    warning: warning2
  });
  let raw;
  try {
    if (name.endsWith(".pdf")) raw = await pdfRead(await file.arrayBuffer(), where);
    else if (name.endsWith(".docx")) raw = await docxRead(await file.arrayBuffer());
    else if (name.endsWith(".txt") || name.endsWith(".md")) raw = { text: await file.text(), links: [] };
    else if (name.endsWith(".doc")) {
      return empty("Old .doc files cannot be read here. The file is kept for attaching; save it as PDF or .docx to have your details read from it.");
    } else return empty("Use a PDF or .docx file to have your details read from it.");
  } catch (err) {
    return empty(`Could not read that file (${err instanceof Error ? err.message : String(err)}). It is kept for attaching; fill your details in by hand.`);
  }
  const text = cleanResumeText(stripControlChars(raw.text)).text;
  const profile = profileFromResume(text, { links: raw.links, today });
  const warning = text.length < 200 ? "Almost no text came out of that file — it may be a scanned image. It is kept for attaching; fill your details in by hand." : null;
  return { text, links: raw.links, profile, warning };
}
export {
  readResume
};
