/**
 * Bulk company list for corpus scale-up.
 *
 * Weighted toward employers that hire across all four families — software,
 * data, cloud and HRIS — rather than only infrastructure. Startups and
 * scale-ups dominate because they cluster on Greenhouse, Lever and Ashby, the
 * three providers with clean public APIs and the fastest probes.
 *
 * Deliberately a static list rather than a live harvest: it is deterministic,
 * costs no third-party dependency, and every name here is a real employer.
 */
export const SCALE_COMPANIES: string[] = [
  // Developer tools, infrastructure, security
  'Postman', 'Insomnia', 'Sourcegraph', 'Codeium', 'Tabnine', 'Sonar', 'Snyk',
  'Mend', 'Checkmarx', 'Veracode', 'Contrast Security', 'Invicti', 'Bugcrowd',
  'HackerOne', 'Detectify', 'Cycode', 'Legit Security', 'Arnica', 'Jit',
  'Nx', 'Turborepo', 'Bit', 'Chromatic', 'Percy', 'Applitools', 'Cypress',
  'Playwright', 'BrowserStack', 'Sauce Labs', 'LambdaTest', 'Testim',
  'Grafana', 'Netdata', 'Better Stack', 'Checkly', 'Cronitor', 'Pingdom',
  'PagerDuty', 'Opsgenie', 'Incident.io', 'FireHydrant', 'Blameless', 'Rootly',
  'Cortex', 'OpsLevel', 'Backstage', 'Humanitec', 'Nobl9', 'Env0',
  'Spacelift', 'Scalr', 'Firefly', 'Infracost', 'Vantage', 'CloudZero',
  'Zesty', 'Cast AI', 'Kubecost', 'Komodor', 'Devtron', 'Codefresh',
  'Harness', 'Octopus Deploy', 'Semaphore', 'Drone', 'Earthly', 'Dagger',
  'Garden', 'Tilt', 'Okteto', 'Signadot', 'Telepresence',
  'Grype', 'Anchore', 'Chainguard', 'Sigstore', 'Tetrate', 'Buoyant',
  'Traefik Labs', 'Emissary', 'Gloo', 'HAProxy', 'Varnish Software',
  'Redpanda', 'StreamNative', 'Conduktor', 'Aiven', 'Instaclustr',
  'Yugabyte', 'SingleStore', 'MariaDB', 'Percona', 'EDB', 'Crunchy Data',
  'Fauna', 'SurrealDB', 'EdgeDB', 'Xata', 'Nile', 'Prisma', 'Drizzle',
  'Hasura', 'PostGraphile', 'Apollo GraphQL', 'StepZen', 'WunderGraph',
  'Temporal Technologies', 'Restate', 'Orkes', 'Camunda', 'Zeebe',
  'Cloudsmith', 'Cloudflare Workers', 'Deno', 'Bun', 'Val Town',
  'Railway', 'Koyeb', 'Zeabur', 'Sevalla', 'Clever Cloud', 'Scaleway',
  'Hetzner', 'OVHcloud', 'Equinix', 'Digital Realty', 'Cyxtera',

  // Data, analytics, AI
  'Fivetran', 'Stitch', 'Matillion', 'Rivery', 'Estuary', 'Meltano',
  'Census', 'Hightouch', 'Polytomic', 'Grouparoo', 'RudderStack',
  'Snowplow', 'Mixpanel', 'PostHog', 'Pendo', 'Contentsquare', 'Quantum Metric',
  'Sigma Computing', 'Omni Analytics', 'Hex', 'Deepnote', 'Count',
  'Preset', 'Metabase', 'Lightdash', 'Cube', 'AtScale', 'Kyligence',
  'Monte Carlo', 'Bigeye', 'Soda', 'Great Expectations', 'Anomalo',
  'Alation', 'Collibra', 'Atlan', 'Select Star', 'Secoda', 'Castor',
  'Starburst', 'Dremio', 'Firebolt', 'Imply', 'Rockset', 'Tinybird',
  'MotherDuck', 'DuckDB Labs', 'Ponder', 'Bodo', 'Voltron Data',
  'Weights and Biases', 'Comet', 'Neptune AI', 'Determined AI', 'ClearML',
  'Arize', 'WhyLabs', 'Fiddler', 'Truera', 'Robust Intelligence',
  'Labelbox', 'Snorkel AI', 'Scale AI', 'Surge AI', 'Toloka', 'Encord',
  'Roboflow', 'Voxel51', 'Lightly', 'Cleanlab', 'Galileo',
  'Anyscale', 'Modal Labs', 'Replicate', 'Banana', 'RunPod', 'Lambda Labs',
  'CoreWeave', 'Crusoe Energy', 'Together AI', 'Fireworks AI', 'Groq',
  'Cerebras', 'SambaNova', 'Graphcore', 'Tenstorrent', 'Etched',
  'Pinecone', 'Weaviate', 'Qdrant', 'Zilliz', 'Marqo', 'Vespa',
  'LlamaIndex', 'Haystack', 'Vellum', 'Humanloop', 'Braintrust', 'Langfuse',
  'Writer', 'Jasper', 'Copy.ai', 'Typeface', 'Regie.ai',
  'Synthesia', 'HeyGen', 'ElevenLabs', 'Descript', 'Suno', 'Udio',
  'Adept', 'Imbue', 'Magic', 'Poolside', 'Augment Code', 'Cognition',

  // Fintech, insurtech, proptech
  'Wise', 'Revolut', 'Monzo', 'Starling Bank', 'N26', 'Bunq',
  'Nubank', 'Klarna', 'Adyen', 'Checkout.com', 'Mollie', 'GoCardless',
  'Airwallex', 'Rapyd', 'Thunes', 'dLocal', 'Payoneer', 'Remitly',
  'Wealthsimple', 'Public.com', 'eToro', 'Interactive Brokers', 'Tastytrade',
  'AlphaSense', 'Addepar', 'iCapital', 'Ethic', 'Vise', 'Altruist',
  'Pilot', 'Bench', 'Puzzle', 'Numeric', 'Mosaic', 'Runway Financial',
  'Vic.ai', 'Tipalti', 'Airbase', 'Center', 'Extend', 'Emburse',
  'Lemonade', 'Root Insurance', 'Hippo', 'Kin Insurance', 'Next Insurance',
  'Pie Insurance', 'Coalition', 'At-Bay', 'Corvus Insurance', 'Newfront',
  'Ethos Life', 'Bestow', 'Ladder Life', 'Policygenius', 'Sure',
  'Clearcover', 'Branch Insurance', 'Openly', 'Slide Insurance',
  'Doma', 'States Title', 'Qualia', 'Endpoint', 'Notarize',
  'VTS', 'Matterport', 'CoStar Group', 'Zumper', 'Apartment List',
  'Latch', 'SmartRent', 'ADT', 'Vivint', 'Alarm.com',

  // Healthcare, biotech, life sciences
  'Oscar', 'Bright Health', 'Alignment Health', 'Aledade', 'Privia Health',
  'Agilon Health', 'VillageMD', 'Cano Health', 'Oak Street Health',
  'Forward Health', 'Parsley Health', 'Everlywell', 'LetsGetChecked',
  'Truepill', 'Alto Pharmacy', 'Capsule', 'NowRx', 'Medly',
  'Grow Therapy', 'Alma', 'Talkspace', 'BetterHelp', 'Brightside Health',
  'Lyra', 'Modern Health', 'Calm Health', 'Big Health', 'Woebot Health',
  'Tia', 'Midi Health', 'Progyny', 'Carrot Fertility', 'Maven',
  'Ophelia', 'Bicycle Health', 'Workit Health', 'Boulder Care',
  'Notable Health', 'Regard', 'Abridge', 'Nabla', 'Suki AI', 'Augmedix',
  'Innovaccer', 'Health Catalyst', 'Arcadia', 'Clarify Health', 'Truveta',
  'Verana Health', 'Aetion', 'Medidata', 'Veeva Systems', 'IQVIA',
  'Parexel', 'ICON plc', 'Syneos Health', 'Fortrea', 'Labcorp',
  'Quest Diagnostics', 'Guardant Health', 'Natera', 'Invitae', 'Myriad Genetics',
  'Illumina', 'Pacific Biosciences', 'Oxford Nanopore', '10x Genomics',
  'Twist Bioscience', 'Synthego', 'Emerald Cloud Lab', 'Strateos',
  'Insitro', 'Genesis Therapeutics', 'Isomorphic Labs', 'Schrodinger',
  'Relay Therapeutics', 'Nimbus Therapeutics', 'Treeline Biosciences',

  // Commerce, marketplaces, logistics, travel
  'Klaviyo', 'Attentive', 'Postscript', 'Yotpo', 'Okendo', 'Loop Returns',
  'Recharge', 'Bold Commerce', 'Swell', 'Fast Simon', 'Searchspring',
  'Algolia', 'Constructor', 'Bloomreach', 'Coveo', 'Lucidworks',
  'Commercetools', 'Fabric', 'Elastic Path', 'VTEX', 'Spryker',
  'Mirakl', 'Marketplacer', 'Nautical Commerce', 'Rithum',
  'ShipStation', 'EasyPost', 'Shipium', 'Flowspace', 'Ryder E-commerce',
  'Nuvocargo', 'Loadsmart', 'Transfix', 'Uber Freight', 'Arrive Logistics',
  'FourKites', 'Tive', 'Overhaul', 'Altana', 'Flexe',
  'Booking Holdings', 'Expedia Group', 'TripAdvisor', 'Kayak', 'Skyscanner',
  'Hopper', 'GetYourGuide', 'Klook', 'Viator', 'Sonder', 'Vacasa',
  'Mews', 'Cloudbeds', 'SiteMinder', 'Duetto', 'Lighthouse',
  'Toast', 'Olo', 'SpotOn', 'Lightspeed Commerce', 'TouchBistro',
  'Wonder', 'Sweetgreen', 'Cava', 'Shake Shack', 'Portillos',

  // SaaS, productivity, HR tech, security
  'Atlassian', 'Smartsheet', 'Wrike', 'Teamwork', 'Basecamp', 'Height',
  'Shortcut', 'Productboard', 'Aha!', 'Craft.io', 'Dovetail', 'Maze',
  'UserTesting', 'Sprig', 'Hotjar', 'Fullview', 'LogRocket',
  'Vanta', 'Drata', 'Secureframe', 'Sprinto', 'Thoropass', 'Scrut',
  'SafeBase', 'Conveyor', 'Whistic', 'Panorays', 'SecurityScorecard',
  'BitSight', 'RiskRecon', 'UpGuard', 'Prevalent', 'OneTrust',
  'Transcend', 'Ketch', 'DataGrail', 'Osano', 'Didomi',
  'Workato', 'Tray.io', 'Boomi', 'Celigo', 'Jitterbit', 'SnapLogic',
  'MuleSoft', 'Zapier', 'Make', 'n8n', 'Pipedream', 'Paragon',
  'Merge', 'Nango', 'Finch', 'Kombo', 'Apideck', 'Unified.to',
  'Lattice', 'Culture Amp', '15Five', 'Leapsome', 'Betterworks',
  'Bob', 'Personio', 'Factorial', 'Charlie HR', 'Humaans', 'Sesame HR',
  'Deel', 'Remote', 'Velocity Global', 'Globalization Partners', 'Papaya Global',
  'Multiplier', 'Atlas HXM', 'Safeguard Global', 'Omnipresent',
  'Greenhouse', 'Lever', 'Ashby', 'Gem', 'SeekOut', 'hireEZ',
  'Findem', 'Fetcher', 'Metaview', 'BrightHire', 'Karat', 'CodeSignal',
  'HackerRank', 'CoderPad', 'Woven', 'Byteboard', 'Otta', 'Welcome to the Jungle',
  'Checkr', 'Certn', 'Veriff', 'Persona', 'Socure', 'Alloy',

  // Enterprise, consultancies, systems integrators
  'Slalom', 'Thoughtworks', 'EPAM Systems', 'Globant', 'Endava', 'Luxoft',
  'GlobalLogic', 'Mphasis', 'LTIMindtree', 'Hexaware', 'Zensar',
  'Persistent Systems', 'Virtusa', 'UST Global', 'Coforge', 'Birlasoft',
  'Tech Mahindra', 'HCLTech', 'Genpact', 'WNS', 'Firstsource',
  'Insight Enterprises', 'CDW', 'SHI International', 'Presidio', 'ePlus',
  'World Wide Technology', 'Optiv', 'GuidePoint Security', 'Trace3',
  'Rackspace Technology', 'Ensono', 'Navisite', 'ClearScale', 'Mission Cloud',
  'Cloudreach', 'Onica', 'Effectual', 'Innovative Solutions',
];
