/**
 * Second bulk company list.
 *
 * Adds breadth the first two lists lacked: mid-market SaaS, regional banks and
 * health systems, universities, staffing and consulting firms, and non-US
 * scale-ups. Enterprises and institutions are deliberately over-represented
 * here — HRIS roles live at banks, hospitals and universities, and the tech-only
 * corpus produced just 17 of them.
 */
export const SCALE2_COMPANIES: string[] = [
  // Mid-market and enterprise SaaS
  'Docusign', 'Dropbox', 'Box', 'Egnyte', 'Nextcloud', 'ownCloud',
  'Zoom', 'RingCentral', 'Dialpad', 'Aircall', 'Talkdesk', 'Five9',
  'Genesys', 'NICE', 'Verint', 'Calabrio', 'Playvox', 'Assembled',
  'Freshworks', 'Zoho', 'SugarCRM', 'Pipedrive', 'Close', 'Copper',
  'Insightly', 'Nutshell', 'Keap', 'ActiveCampaign', 'Omnisend',
  'Mailchimp', 'Constant Contact', 'Brevo', 'MailerLite', 'Beehiiv',
  'ConvertKit', 'Ghost', 'Buttondown', 'Substack', 'Memberful',
  'Hootsuite', 'Buffer', 'Later', 'Sprout Social', 'Emplifi', 'Dash Hudson',
  'Semrush', 'Ahrefs', 'Moz', 'Similarweb', 'Conductor', 'BrightEdge',
  'Yext', 'Birdeye', 'Podium', 'Reputation', 'Trustpilot', 'Bazaarvoice',
  'Qualtrics', 'Medallia', 'InMoment', 'Alchemer', 'SurveyMonkey', 'Typeform',
  'Airtable', 'Coda', 'Slite', 'Nuclino', 'Almanac', 'Guru',
  'Confluence', 'Notion Labs', 'Obsidian', 'Roam Research', 'Mem',
  'Lucid Software', 'Miro', 'FigJam', 'Whimsical', 'Excalidraw',
  'Mural', 'Creately', 'Visme', 'Beautiful.ai', 'Pitch', 'Tome',
  'Gamma', 'Canva', 'VistaPrint', 'Cimpress', 'Shutterstock', 'Getty Images',
  'Unsplash', 'Envato', 'Creative Market', 'Adobe', 'Corel',
  'Autodesk', 'Bentley Systems', 'Trimble', 'Hexagon AB', 'Dassault Systemes',
  'PTC', 'Ansys', 'Altair', 'Siemens Digital Industries', 'Onshape',
  'Fusion 360', 'Shapr3D', 'nTop', 'Markforged', 'Formlabs', 'Desktop Metal',
  'Carbon', 'Velo3D', 'Xometry', 'Protolabs', 'Fictiv', 'Hubs',

  // Regional banks, credit unions, financial institutions
  'Comerica', 'Zions Bancorporation', 'First Horizon', 'Synovus', 'Valley National Bank',
  'Webster Bank', 'East West Bank', 'Cathay General Bancorp', 'BankUnited',
  'Pinnacle Financial Partners', 'South State Bank', 'United Bankshares',
  'FNB Corporation', 'Old National Bank', 'Associated Bank', 'BOK Financial',
  'Cullen Frost Bankers', 'Prosperity Bancshares', 'Glacier Bancorp',
  'Home BancShares', 'Simmons Bank', 'Ameris Bancorp', 'Axos Financial',
  'Navy Federal Credit Union', 'PenFed Credit Union', 'SchoolsFirst',
  'Golden 1 Credit Union', 'Alliant Credit Union', 'BECU', 'Suncoast Credit Union',
  'Raymond James', 'LPL Financial', 'Stifel', 'Jefferies', 'Piper Sandler',
  'Evercore', 'Lazard', 'Houlihan Lokey', 'Moelis', 'PJT Partners',
  'Apollo Global Management', 'Blackstone', 'KKR', 'Carlyle Group', 'TPG',
  'Ares Management', 'Brookfield', 'Blue Owl', 'Golub Capital',
  'Franklin Templeton', 'T Rowe Price', 'Invesco', 'Janus Henderson',
  'AllianceBernstein', 'Neuberger Berman', 'PGIM', 'Nuveen', 'MFS',
  'Moodys', 'S&P Global', 'MSCI', 'FactSet', 'Morningstar', 'Verisk',
  'TransUnion', 'Equifax', 'Experian', 'Fair Isaac', 'LexisNexis Risk Solutions',

  // Health systems, providers, payers
  'Memorial Hermann', 'Houston Methodist', 'Baptist Health', 'AdventHealth',
  'Orlando Health', 'BayCare Health System', 'Tampa General Hospital',
  'Cedars-Sinai', 'City of Hope', 'Scripps Health', 'Sharp HealthCare',
  'UC San Diego Health', 'Stanford Health Care', 'UCSF Health', 'Sutter Health',
  'Dignity Health', 'Hoag', 'MemorialCare', 'Cottage Health',
  'Rush University Medical Center', 'Endeavor Health', 'Loyola Medicine',
  'Henry Ford Health', 'Beaumont Health', 'Michigan Medicine', 'Spectrum Health',
  'Allina Health', 'HealthPartners', 'Essentia Health', 'Sanford Health',
  'Froedtert', 'Aurora Health Care', 'Marshfield Clinic', 'Gundersen Health',
  'Ochsner Health', 'LCMC Health', 'Tulane Medical Center', 'Willis-Knighton',
  'WellSpan Health', 'Penn Medicine', 'Jefferson Health', 'Temple Health',
  'Nemours', 'ChristianaCare', 'MedStar Health', 'Inova', 'Sentara Healthcare',
  'VCU Health', 'Duke Health', 'UNC Health', 'WakeMed', 'Cone Health',
  'Prisma Health', 'MUSC Health', 'Emory Healthcare', 'Piedmont Healthcare',
  'Wellstar Health System', 'Northside Hospital', 'Grady Health System',
  'Vanderbilt Health', 'Ballad Health', 'Methodist Le Bonheur',
  'Norton Healthcare', 'UK HealthCare', 'UofL Health', 'Bon Secours Mercy Health',
  'OhioHealth', 'Nationwide Childrens Hospital', 'ProMedica', 'Summa Health',
  'Indiana University Health', 'Community Health Network', 'Parkview Health',
  'Corewell', 'Trinity Health Michigan', 'Beacon Health System',
  'SSM Health', 'Mercy', 'BJC HealthCare', 'CoxHealth', 'Saint Lukes Health System',
  'University of Kansas Health System', 'Stormont Vail Health',
  'Intermountain Healthcare', 'University of Utah Health', 'Banner Health',
  'HonorHealth', 'Valleywise Health', 'Dignity Health Arizona',
  'Providence', 'MultiCare', 'Overlake Medical Center', 'Virginia Mason',
  'Legacy Health', 'Salem Health', 'Asante', 'PeaceHealth',
  'Renown Health', 'University Medical Center', 'Presbyterian Healthcare Services',

  // Universities and research institutions
  'Massachusetts Institute of Technology', 'California Institute of Technology',
  'Princeton University', 'University of Pennsylvania', 'Cornell University',
  'Brown University', 'Dartmouth College', 'Rice University',
  'Washington University in St Louis', 'University of Notre Dame',
  'Georgia Institute of Technology', 'University of Virginia',
  'University of North Carolina', 'Wake Forest University',
  'Tufts University', 'Brandeis University', 'Case Western Reserve University',
  'University of Rochester', 'Rensselaer Polytechnic Institute',
  'Worcester Polytechnic Institute', 'Stevens Institute of Technology',
  'Rutgers University', 'University of Maryland', 'George Washington University',
  'American University', 'Howard University', 'Johns Hopkins University',
  'University of Pittsburgh', 'Drexel University', 'Villanova University',
  'University of Delaware', 'University of Connecticut', 'Northeastern University',
  'Boston College', 'University of Massachusetts', 'Syracuse University',
  'University at Buffalo', 'Stony Brook University', 'Fordham University',
  'Columbia Engineering', 'The New School', 'Pace University',
  'University of Illinois', 'University of Wisconsin', 'University of Minnesota',
  'University of Iowa', 'Iowa State University', 'University of Nebraska',
  'University of Missouri', 'University of Kansas', 'Kansas State University',
  'University of Oklahoma', 'Oklahoma State University', 'University of Arkansas',
  'Texas A&M University', 'University of Texas', 'Baylor University',
  'Southern Methodist University', 'Texas Tech University', 'University of Houston',
  'Arizona State University', 'University of Arizona', 'University of Colorado',
  'Colorado State University', 'University of Denver', 'University of Utah',
  'Brigham Young University', 'University of Nevada', 'University of Oregon',
  'Oregon State University', 'University of Washington', 'Washington State University',
  'University of California Berkeley', 'UCLA', 'UC Davis', 'UC Irvine',
  'University of Southern California', 'Santa Clara University', 'Pepperdine University',
  'University of Florida', 'Florida State University', 'University of Miami',
  'University of Central Florida', 'University of South Florida',
  'University of Georgia', 'Auburn University', 'University of Alabama',
  'Clemson University', 'University of South Carolina', 'University of Tennessee',
  'University of Kentucky', 'Ohio State University Wexner', 'Purdue Research Foundation',
  'Michigan State University', 'Wayne State University', 'Northern Illinois University',

  // Staffing, consulting, professional services
  'Robert Half', 'Kforce', 'TEKsystems', 'Insight Global', 'Aerotek',
  'Randstad', 'Adecco', 'ManpowerGroup', 'Kelly Services', 'Hays',
  'Michael Page', 'Robert Walters', 'Korn Ferry', 'Heidrick and Struggles',
  'Egon Zehnder', 'Spencer Stuart', 'Russell Reynolds', 'Odgers Berndtson',
  'Deloitte', 'PwC', 'EY', 'KPMG', 'Grant Thornton', 'BDO', 'RSM US',
  'Crowe', 'Baker Tilly', 'Moss Adams', 'CliftonLarsonAllen', 'Plante Moran',
  'Protiviti', 'Alvarez and Marsal', 'AlixPartners', 'FTI Consulting',
  'Huron Consulting', 'Navigant', 'Charles River Associates', 'Analysis Group',
  'McKinsey', 'Bain', 'Boston Consulting Group', 'Oliver Wyman', 'LEK Consulting',
  'Roland Berger', 'Arthur D Little', 'Kearney', 'ZS Associates',
  'Publicis Sapient', 'Infosys Consulting', 'Capco', 'Synechron', 'Iris Software',

  // International scale-ups and enterprises
  'Spotify Technology', 'Klarna Bank', 'Northvolt', 'Einride', 'Voi Technology',
  'Truecaller', 'Kry', 'Tink', 'Trustly', 'iZettle', 'Budbee',
  'Zalando', 'Delivery Hero', 'HelloFresh', 'GetYourGuide GmbH', 'Trade Republic',
  'Solaris', 'Raisin', 'Scalable Capital', 'Wefox', 'Getsafe',
  'Celonis', 'Signavio', 'Camunda Services', 'Contentful GmbH', 'Commercetools GmbH',
  'SoundCloud', 'Ableton', 'Native Instruments', 'Bitwig',
  'Adyen NV', 'Backbase', 'Bynder', 'Mendix', 'MessageBird', 'Bird',
  'Picnic', 'Bolt Technology', 'Wolt', 'Vinted', 'Nord Security',
  'Kilo Health', 'Hostinger', 'Omnisend UAB', 'Whatagraph',
  'UiPath', 'Bitdefender', 'Endava Romania', 'FintechOS', 'Druid AI',
  'Zenitech', 'Emag', 'Bolt Romania', 'Cognizant Romania',
  'Grab', 'Sea Group', 'GoTo Group', 'Traveloka', 'Carousell', 'Ninja Van',
  'Coda Payments', 'Nium', 'Aspire', 'Endowus', 'StashAway',
  'Atlassian Corporation', 'Canva Australia', 'SafetyCulture', 'Culture Amp Australia',
  'Airwallex Australia', 'Employment Hero', 'Deputy', 'Rokt', 'Linktree',
  'Xero', 'Vend', 'Pushpay', 'Halter', 'Rocket Lab', 'Sharesies',
];
